/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protocol.pb-c.h"
void   mtsc__config__init
                     (Mtsc__Config         *message)
{
  static const Mtsc__Config init_value = MTSC__CONFIG__INIT;
  *message = init_value;
}
size_t mtsc__config__get_packed_size
                     (const Mtsc__Config *message)
{
  assert(message->base.descriptor == &mtsc__config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mtsc__config__pack
                     (const Mtsc__Config *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mtsc__config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mtsc__config__pack_to_buffer
                     (const Mtsc__Config *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mtsc__config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mtsc__Config *
       mtsc__config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mtsc__Config *)
     protobuf_c_message_unpack (&mtsc__config__descriptor,
                                allocator, len, data);
}
void   mtsc__config__free_unpacked
                     (Mtsc__Config *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mtsc__config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mtsc__datas__init
                     (Mtsc__Datas         *message)
{
  static const Mtsc__Datas init_value = MTSC__DATAS__INIT;
  *message = init_value;
}
size_t mtsc__datas__get_packed_size
                     (const Mtsc__Datas *message)
{
  assert(message->base.descriptor == &mtsc__datas__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mtsc__datas__pack
                     (const Mtsc__Datas *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mtsc__datas__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mtsc__datas__pack_to_buffer
                     (const Mtsc__Datas *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mtsc__datas__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Mtsc__Datas *
       mtsc__datas__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Mtsc__Datas *)
     protobuf_c_message_unpack (&mtsc__datas__descriptor,
                                allocator, len, data);
}
void   mtsc__datas__free_unpacked
                     (Mtsc__Datas *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mtsc__datas__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mtsc__config__field_descriptors[35] =
{
  {
    "bikeName",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Mtsc__Config, bikename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bikeNameBLE",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Mtsc__Config, bikenameble),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vin",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Mtsc__Config, vin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "idRFID1",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Mtsc__Config, idrfid1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "idRFID2",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Mtsc__Config, idrfid2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "idRFID3",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Mtsc__Config, idrfid3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "idRFID4",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Mtsc__Config, idrfid4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ccid",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Mtsc__Config, ccid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "brakingForce",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_brakingforce),
    offsetof(Mtsc__Config, brakingforce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "brakingTrigger",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Mtsc__Config, has_brakingtrigger),
    offsetof(Mtsc__Config, brakingtrigger),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "testmode",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Mtsc__Config, has_testmode),
    offsetof(Mtsc__Config, testmode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currentTrig",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_currenttrig),
    offsetof(Mtsc__Config, currenttrig),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "torkCoeff",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_torkcoeff),
    offsetof(Mtsc__Config, torkcoeff),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "torkIntCoeff",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_torkintcoeff),
    offsetof(Mtsc__Config, torkintcoeff),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speedCoeff",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_speedcoeff),
    offsetof(Mtsc__Config, speedcoeff),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ecoCurrent",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_ecocurrent),
    offsetof(Mtsc__Config, ecocurrent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "brakeCurrent",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_brakecurrent),
    offsetof(Mtsc__Config, brakecurrent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ecoTorkSlope",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_ecotorkslope),
    offsetof(Mtsc__Config, ecotorkslope),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "normTorkSlope",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_normtorkslope),
    offsetof(Mtsc__Config, normtorkslope),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sporTorkSlope",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_sportorkslope),
    offsetof(Mtsc__Config, sportorkslope),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxCurrent",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_maxcurrent),
    offsetof(Mtsc__Config, maxcurrent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speedMultiplier",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_speedmultiplier),
    offsetof(Mtsc__Config, speedmultiplier),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tripMultiplier",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_tripmultiplier),
    offsetof(Mtsc__Config, tripmultiplier),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "brakingState",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Mtsc__Config, has_brakingstate),
    offsetof(Mtsc__Config, brakingstate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currPercDegraded",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_currpercdegraded),
    offsetof(Mtsc__Config, currpercdegraded),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tempStartDegraded",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_tempstartdegraded),
    offsetof(Mtsc__Config, tempstartdegraded),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tempStopDegraded",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_tempstopdegraded),
    offsetof(Mtsc__Config, tempstopdegraded),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperatureEmergency",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_temperatureemergency),
    offsetof(Mtsc__Config, temperatureemergency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "degrTorkEcoSlope",
    29,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_degrtorkecoslope),
    offsetof(Mtsc__Config, degrtorkecoslope),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "degrTorkNormSlope",
    30,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_degrtorknormslope),
    offsetof(Mtsc__Config, degrtorknormslope),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "degrTorkSportSlope",
    31,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_degrtorksportslope),
    offsetof(Mtsc__Config, degrtorksportslope),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "degrMaxCurrent",
    32,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_degrmaxcurrent),
    offsetof(Mtsc__Config, degrmaxcurrent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "degrCurrTrig",
    33,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_degrcurrtrig),
    offsetof(Mtsc__Config, degrcurrtrig),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "betaFactor",
    34,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Mtsc__Config, has_betafactor),
    offsetof(Mtsc__Config, betafactor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resetConfig",
    35,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Mtsc__Config, has_resetconfig),
    offsetof(Mtsc__Config, resetconfig),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mtsc__config__field_indices_by_name[] = {
  33,   /* field[33] = betaFactor */
  0,   /* field[0] = bikeName */
  1,   /* field[1] = bikeNameBLE */
  16,   /* field[16] = brakeCurrent */
  8,   /* field[8] = brakingForce */
  23,   /* field[23] = brakingState */
  9,   /* field[9] = brakingTrigger */
  7,   /* field[7] = ccid */
  24,   /* field[24] = currPercDegraded */
  11,   /* field[11] = currentTrig */
  32,   /* field[32] = degrCurrTrig */
  31,   /* field[31] = degrMaxCurrent */
  28,   /* field[28] = degrTorkEcoSlope */
  29,   /* field[29] = degrTorkNormSlope */
  30,   /* field[30] = degrTorkSportSlope */
  15,   /* field[15] = ecoCurrent */
  17,   /* field[17] = ecoTorkSlope */
  3,   /* field[3] = idRFID1 */
  4,   /* field[4] = idRFID2 */
  5,   /* field[5] = idRFID3 */
  6,   /* field[6] = idRFID4 */
  20,   /* field[20] = maxCurrent */
  18,   /* field[18] = normTorkSlope */
  34,   /* field[34] = resetConfig */
  14,   /* field[14] = speedCoeff */
  21,   /* field[21] = speedMultiplier */
  19,   /* field[19] = sporTorkSlope */
  25,   /* field[25] = tempStartDegraded */
  26,   /* field[26] = tempStopDegraded */
  27,   /* field[27] = temperatureEmergency */
  10,   /* field[10] = testmode */
  12,   /* field[12] = torkCoeff */
  13,   /* field[13] = torkIntCoeff */
  22,   /* field[22] = tripMultiplier */
  2,   /* field[2] = vin */
};
static const ProtobufCIntRange mtsc__config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 35 }
};
const ProtobufCMessageDescriptor mtsc__config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mtsc.Config",
  "Config",
  "Mtsc__Config",
  "mtsc",
  sizeof(Mtsc__Config),
  35,
  mtsc__config__field_descriptors,
  mtsc__config__field_indices_by_name,
  1,  mtsc__config__number_ranges,
  (ProtobufCMessageInit) mtsc__config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mtsc__datas__field_descriptors[10] =
{
  {
    "powerMode",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Mtsc__Datas, has_powermode),
    offsetof(Mtsc__Datas, powermode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "assistMode",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Mtsc__Datas, has_assistmode),
    offsetof(Mtsc__Datas, assistmode),
    &mtsc__assist_modes__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minutes",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Mtsc__Datas, has_minutes),
    offsetof(Mtsc__Datas, minutes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hours",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Mtsc__Datas, has_hours),
    offsetof(Mtsc__Datas, hours),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "weath",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Mtsc__Datas, has_weath),
    offsetof(Mtsc__Datas, weath),
    &mtsc__weather__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "odo",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Mtsc__Datas, has_odo),
    offsetof(Mtsc__Datas, odo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tripA",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Mtsc__Datas, has_tripa),
    offsetof(Mtsc__Datas, tripa),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tripB",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Mtsc__Datas, has_tripb),
    offsetof(Mtsc__Datas, tripb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "soc",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Mtsc__Datas, has_soc),
    offsetof(Mtsc__Datas, soc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "erpm",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Mtsc__Datas, has_erpm),
    offsetof(Mtsc__Datas, erpm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mtsc__datas__field_indices_by_name[] = {
  1,   /* field[1] = assistMode */
  9,   /* field[9] = erpm */
  3,   /* field[3] = hours */
  2,   /* field[2] = minutes */
  5,   /* field[5] = odo */
  0,   /* field[0] = powerMode */
  8,   /* field[8] = soc */
  6,   /* field[6] = tripA */
  7,   /* field[7] = tripB */
  4,   /* field[4] = weath */
};
static const ProtobufCIntRange mtsc__datas__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor mtsc__datas__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mtsc.Datas",
  "Datas",
  "Mtsc__Datas",
  "mtsc",
  sizeof(Mtsc__Datas),
  10,
  mtsc__datas__field_descriptors,
  mtsc__datas__field_indices_by_name,
  1,  mtsc__datas__number_ranges,
  (ProtobufCMessageInit) mtsc__datas__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue mtsc__weather__enum_values_by_number[4] =
{
  { "WE_SUN", "MTSC__WEATHER__WE_SUN", 0 },
  { "WE_RAIN", "MTSC__WEATHER__WE_RAIN", 1 },
  { "WE_SNOW", "MTSC__WEATHER__WE_SNOW", 2 },
  { "WE_STORM", "MTSC__WEATHER__WE_STORM", 3 },
};
static const ProtobufCIntRange mtsc__weather__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex mtsc__weather__enum_values_by_name[4] =
{
  { "WE_RAIN", 1 },
  { "WE_SNOW", 2 },
  { "WE_STORM", 3 },
  { "WE_SUN", 0 },
};
const ProtobufCEnumDescriptor mtsc__weather__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "mtsc.Weather",
  "Weather",
  "Mtsc__Weather",
  "mtsc",
  4,
  mtsc__weather__enum_values_by_number,
  4,
  mtsc__weather__enum_values_by_name,
  1,
  mtsc__weather__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue mtsc__assist_modes__enum_values_by_number[3] =
{
  { "AM_NORMAL", "MTSC__ASSIST_MODES__AM_NORMAL", 0 },
  { "AM_SPORT", "MTSC__ASSIST_MODES__AM_SPORT", 1 },
  { "AM_ECO", "MTSC__ASSIST_MODES__AM_ECO", 2 },
};
static const ProtobufCIntRange mtsc__assist_modes__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex mtsc__assist_modes__enum_values_by_name[3] =
{
  { "AM_ECO", 2 },
  { "AM_NORMAL", 0 },
  { "AM_SPORT", 1 },
};
const ProtobufCEnumDescriptor mtsc__assist_modes__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "mtsc.AssistModes",
  "AssistModes",
  "Mtsc__AssistModes",
  "mtsc",
  3,
  mtsc__assist_modes__enum_values_by_number,
  3,
  mtsc__assist_modes__enum_values_by_name,
  1,
  mtsc__assist_modes__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
