/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol.proto */

#ifndef PROTOBUF_C_protocol_2eproto__INCLUDED
#define PROTOBUF_C_protocol_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Mtsc__Config Mtsc__Config;
typedef struct Mtsc__Datas Mtsc__Datas;


/* --- enums --- */

typedef enum _Mtsc__Weather {
  MTSC__WEATHER__WE_SUN = 0,
  MTSC__WEATHER__WE_RAIN = 1,
  MTSC__WEATHER__WE_SNOW = 2,
  MTSC__WEATHER__WE_STORM = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MTSC__WEATHER)
} Mtsc__Weather;
typedef enum _Mtsc__AssistModes {
  MTSC__ASSIST_MODES__AM_NORMAL = 0,
  MTSC__ASSIST_MODES__AM_SPORT = 1,
  MTSC__ASSIST_MODES__AM_ECO = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MTSC__ASSIST_MODES)
} Mtsc__AssistModes;

/* --- messages --- */

struct  Mtsc__Config
{
  ProtobufCMessage base;
  /*
   * name shown at the starting on the bike (max 10 chars)
   */
  char *bikename;
  /*
   * name on bluetooth max 11char + \0
   */
  char *bikenameble;
  /*
   * bike's vin number
   */
  char *vin;
  /*
   * RFID badge, usefull for setting it through BLE
   */
  char *idrfid1;
  /*
   * RFID badge, usefull for setting it through BLE
   */
  char *idrfid2;
  /*
   * RFID badge, usefull for setting it through BLE
   */
  char *idrfid3;
  /*
   * RFID badge, usefull for setting it through BLE
   */
  char *idrfid4;
  /*
   * CCID of the eSIM of Trac'y module
   */
  char *ccid;
  /*
   * braking force
   */
  /*
   * deprecated, use brakeCurrent instead
   */
  protobuf_c_boolean has_brakingforce;
  float brakingforce;
  /*
   * if true, each brake = 50% of braking force, if false always 100% of braking force 
   */
  protobuf_c_boolean has_brakingtrigger;
  protobuf_c_boolean brakingtrigger;
  /*
   * if necessary, could help for debug 
   */
  protobuf_c_boolean has_testmode;
  uint32_t testmode;
  /*
   * drive-train parameters, must be hidden from user
   */
  /*
   * percentage of current at which the motor starts spinning
   */
  protobuf_c_boolean has_currenttrig;
  float currenttrig;
  /*
   * tork proportional coefficient of the PID controller
   */
  protobuf_c_boolean has_torkcoeff;
  float torkcoeff;
  /*
   * tork integral coefficient of the PID controller  
   */
  protobuf_c_boolean has_torkintcoeff;
  float torkintcoeff;
  /*
   * speed proportional coefficient of the PID controller
   */
  protobuf_c_boolean has_speedcoeff;
  float speedcoeff;
  /*
   * maximum current for eco mode (percentage of the maximum current)
   */
  protobuf_c_boolean has_ecocurrent;
  float ecocurrent;
  /*
   * the regen current in amps
   */
  protobuf_c_boolean has_brakecurrent;
  float brakecurrent;
  /*
   * the slope of the eco mode 
   */
  protobuf_c_boolean has_ecotorkslope;
  float ecotorkslope;
  /*
   * the slope of the normal mode 
   */
  protobuf_c_boolean has_normtorkslope;
  float normtorkslope;
  /*
   * the slope of the sport mode 
   */
  protobuf_c_boolean has_sportorkslope;
  float sportorkslope;
  /*
   * maximum current used for tork sensor's accuracy (max current limited in VESC!)
   */
  protobuf_c_boolean has_maxcurrent;
  float maxcurrent;
  /*
   * the speed multiplier 
   */
  protobuf_c_boolean has_speedmultiplier;
  float speedmultiplier;
  /*
   * the trip multiplier 
   */
  protobuf_c_boolean has_tripmultiplier;
  float tripmultiplier;
  /*
   * set it to 1 if brakes are normally open, to 0 if normally closed
   */
  protobuf_c_boolean has_brakingstate;
  uint32_t brakingstate;
  /*
   * % of authorized current when degraded mode 
   */
  protobuf_c_boolean has_currpercdegraded;
  float currpercdegraded;
  /*
   * temperature at which the degraded mode is effectif
   */
  protobuf_c_boolean has_tempstartdegraded;
  float tempstartdegraded;
  /*
   * temperature at which the degraded mode turns off
   */
  protobuf_c_boolean has_tempstopdegraded;
  float tempstopdegraded;
  /*
   * temperature at which we stop spining the motor
   */
  protobuf_c_boolean has_temperatureemergency;
  float temperatureemergency;
  protobuf_c_boolean has_degrtorkecoslope;
  float degrtorkecoslope;
  protobuf_c_boolean has_degrtorknormslope;
  float degrtorknormslope;
  protobuf_c_boolean has_degrtorksportslope;
  float degrtorksportslope;
  protobuf_c_boolean has_degrmaxcurrent;
  float degrmaxcurrent;
  protobuf_c_boolean has_degrcurrtrig;
  float degrcurrtrig;
  protobuf_c_boolean has_betafactor;
  float betafactor;
  /*
   * factor which set minimum current when hitting the temperatureEmergency value ( 1 - (temp-tempStartDegraded) / betaFactor*(temperatureEmergency-tempStartDegraded))
   */
  protobuf_c_boolean has_resetconfig;
  protobuf_c_boolean resetconfig;
};
#define MTSC__CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mtsc__config__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  Mtsc__Datas
{
  ProtobufCMessage base;
  /*
   * if the bike is ON (true) or OFF (false)
   */
  protobuf_c_boolean has_powermode;
  protobuf_c_boolean powermode;
  /*
   * assistance modes: Normal, Sport or Eco
   */
  protobuf_c_boolean has_assistmode;
  Mtsc__AssistModes assistmode;
  protobuf_c_boolean has_minutes;
  uint32_t minutes;
  protobuf_c_boolean has_hours;
  uint32_t hours;
  protobuf_c_boolean has_weath;
  Mtsc__Weather weath;
  /*
   * the odometer in km
   */
  protobuf_c_boolean has_odo;
  double odo;
  /*
   * the trip A in km
   */
  protobuf_c_boolean has_tripa;
  double tripa;
  /*
   * the trip B in km
   */
  protobuf_c_boolean has_tripb;
  double tripb;
  /*
   * state of charge from 0 to 100 %
   */
  protobuf_c_boolean has_soc;
  uint32_t soc;
  /*
   * erpm can be set with specific testmode (only used for testing)
   */
  protobuf_c_boolean has_erpm;
  uint32_t erpm;
};
#define MTSC__DATAS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mtsc__datas__descriptor) \
    , 0, 0, 0, MTSC__ASSIST_MODES__AM_NORMAL, 0, 0, 0, 0, 0, MTSC__WEATHER__WE_SUN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


/* Mtsc__Config methods */
void   mtsc__config__init
                     (Mtsc__Config         *message);
size_t mtsc__config__get_packed_size
                     (const Mtsc__Config   *message);
size_t mtsc__config__pack
                     (const Mtsc__Config   *message,
                      uint8_t             *out);
size_t mtsc__config__pack_to_buffer
                     (const Mtsc__Config   *message,
                      ProtobufCBuffer     *buffer);
Mtsc__Config *
       mtsc__config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mtsc__config__free_unpacked
                     (Mtsc__Config *message,
                      ProtobufCAllocator *allocator);
/* Mtsc__Datas methods */
void   mtsc__datas__init
                     (Mtsc__Datas         *message);
size_t mtsc__datas__get_packed_size
                     (const Mtsc__Datas   *message);
size_t mtsc__datas__pack
                     (const Mtsc__Datas   *message,
                      uint8_t             *out);
size_t mtsc__datas__pack_to_buffer
                     (const Mtsc__Datas   *message,
                      ProtobufCBuffer     *buffer);
Mtsc__Datas *
       mtsc__datas__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mtsc__datas__free_unpacked
                     (Mtsc__Datas *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Mtsc__Config_Closure)
                 (const Mtsc__Config *message,
                  void *closure_data);
typedef void (*Mtsc__Datas_Closure)
                 (const Mtsc__Datas *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    mtsc__weather__descriptor;
extern const ProtobufCEnumDescriptor    mtsc__assist_modes__descriptor;
extern const ProtobufCMessageDescriptor mtsc__config__descriptor;
extern const ProtobufCMessageDescriptor mtsc__datas__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_protocol_2eproto__INCLUDED */
